### ISSUE TITLE
[question]what kind of issue happened with morphdom?

### ISSUE THREAD

**Issue by odyss009** [rill-js/html#1]
I wonder why did you revert back to diffhtml?
What kind of problems happened with morphdom?

Thanks~

**Comment by DylanPiercey** [comment]
I thought I had fixed full page morphs with this PR https://github.com/patrick-steele-idem/morphdom/pull/48 but although the diff works it actually discards all of the old DOM, ie input state lost. I added another comment to my issue so this may be addressed in the future but for now diffhtml works pretty good for me. https://github.com/patrick-steele-idem/morphdom/issues/39#issuecomment-213238527

@odyss009 are you having any issue with diffhtml?

**Comment by DylanPiercey** [comment]
@odyss009 I'm going to close this, if you have any other questions I'd be happy to chat on the [gitter](https://gitter.im/rill-js/rill).

**Comment by odyss009** [comment]
Thanks for explanation.
